In [1]:
import numpy as np


In [3]:
benimDizim = np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [6]:
benimDizim[3:5]

array([3, 4])

In [7]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [8]:
benimDizim[3:8] = -5

In [9]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi = np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
slicingDizi = baskaDizi[4:9]

In [13]:
slicingDizi

array([4, 5, 6, 7, 8])

In [16]:
slicingDizi[::]

array([4, 5, 6, 7, 8])

In [17]:
slicingDizi[:] = 700

In [18]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [19]:
slicingDizi

array([700, 700, 700, 700, 700])

In [21]:
ornekDizi = np.arange(0,24)

In [22]:
ornekDiziKopyasi = ornekDizi.copy()

In [23]:
ornekDizi


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [26]:
ornekDiziKopyaSlicing

array([3, 4, 5])

In [27]:
ornekDiziKopyaSlicing[:] = 800

In [28]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [29]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [30]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [31]:
benimMatrixDizim = np.array(benimListem)

In [32]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [33]:
benimMatrixDizim[0]

array([10, 20, 30])

In [34]:
benimMatrixDizim[1][2]

40

In [35]:
benimMatrixDizim[1,2]

40

In [36]:
benimMatrixDizim[1,2]

40

In [37]:
benimMatrixDizim[1:,2]

array([40, 60])

In [38]:
benimMatrixDizim[0:,1]

array([20, 30, 50])

In [40]:
benimMatrixDizim[2:,1]

array([50])

In [41]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [42]:
yeniMatrix = np.array(yeniListe)

In [43]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
yeniMatrix[[0,2,4]] ## fancy indexing

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Operasyonlar

In [47]:
yeniBirDizi = np.arange(5,25)

In [48]:
yeniBirDizi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [49]:
yeniBirDizi = np.random.randint(1,100,20)

In [50]:
yeniBirDizi

array([95, 84, 21, 39, 39, 73, 51, 24, 42, 50, 77, 60, 77, 92,  6,  8, 21,
       68, 53, 82])

In [51]:
yeniBirDizi > 24

array([ True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True,  True])

In [52]:
type(yeniBirDizi)

numpy.ndarray

In [53]:
sonucDizisi = yeniBirDizi > 24

In [54]:
sonucDizisi

array([ True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True,  True])

In [55]:
yeniBirDizi[sonucDizisi]

array([95, 84, 39, 39, 73, 51, 42, 50, 77, 60, 77, 92, 68, 53, 82])

In [57]:
yeniBirDizi[yeniBirDizi > 60] ## OMG

array([95, 84, 73, 77, 77, 92, 68, 82])

In [58]:
sonDizi = np.arange(0,24)

In [59]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [61]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [62]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [63]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [64]:
sonDizi / sonDizi

/var/folders/mh/x5vmc6194szf246rdvs1s6n40000gn/T/ipykernel_8302/1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [65]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [66]:
np.sum(sonDizi)

276

In [67]:
np.max(sonDizi)

23

In [68]:
np.min(sonDizi)

0