### Example 1

In [1]:
print("Twinkle, twinkle, little star, \n    How I Wonder what you are! \n       Up Above the world so high \n       Like a diamondin the sky. \nTwinkle, twinkle, little star, \n       How I Wonder what you are")

Twinkle, twinkle, little star, 
    How I Wonder what you are! 
       Up Above the world so high 
       Like a diamondin the sky. 
Twinkle, twinkle, little star, 
       How I Wonder what you are


### Example 2

In [2]:
print(sys.version)

3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]


### Example 3

In [5]:
import datetime


datetime.datetime.now()

datetime.datetime(2022, 10, 23, 0, 57, 1, 951473)

### Example 4

In [6]:
import math


x = float(input("Radius: "))
print(f"Area of circle: {x**2 * math.pi}")

Area of circle: 452.3893421169302


### Example 5

In [7]:
fN = input("İlk İsim: ")
lN = input("Son İsim: ")

print(f"{lN} {fN}")

Korkmaz Yunus


### Example 6

In [15]:
x = input("Giriniz: ")

y = []

xE = x.split(",")

y = xE
z = tuple(y)

print(y)
print(z)

['yunus', 'korkmaz']
('yunus', 'korkmaz')


### Example 7

In [16]:
fullName = input("Say my name: ")
extensionName= fullName.split(".")[-1]
print(extensionName)

apfs


### Example 8

In [17]:
color_list = ["Red","Green","White" ,"Black"]
print(f"First: {color_list[0]} \nSecond: {color_list[-1]}")

First: Red 
Second: Black


### Example 9

In [25]:
deadLine = (16,5,2003)
print("%i/%i/%i"%deadLine)

16/5/2003


### Example 10

In [27]:
x = input("Say A Number: ")

firstNumber = int(x)
secondNumber = int(x + x)
thirdNumber = int(x+x+x)

print(firstNumber+secondNumber+thirdNumber)

615


### Example 11


In [3]:
print(abs.__doc__)


Return the absolute value of the argument.


### Example 12

In [4]:
import calendar


y = int(input("Year: "))
m = int(input("Month: "))

print(calendar.month(y,m))

      May 2003
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31



### Example 13

In [8]:
print("""
Uzun ince bir yoldayım
    Gidiyorum gündüz gece
Bilmiyorum ne haldeyim
    Gidiyorum gündüz gece
""")


Uzun ince bir yoldayım
    Gidiyorum gündüz gece
Bilmiyorum ne haldeyim
    Gidiyorum gündüz gece



### Example 14

In [11]:
import datetime as dt
firstDate = dt.date(2003,5,16)
secondDate = dt.date(2022,10,23)

print(f"My Living Days: {secondDate-firstDate} ")


My Living Days: 7100 days, 0:00:00 


### Example 15

In [12]:
import math as mt
print(mt.pi * 6**3)

678.5840131753953


### Example 16

In [15]:
def weirdFunction(n):
    if n<=17:
        return 17-n
    else:
        return (n-17)*2

print(weirdFunction(10))
print(weirdFunction(30))


7
26


### Example 17

In [17]:
def otherFunc(n):
    if n in list(range(100,1001)):
        return True

print(otherFunc(500))

True


### Example 18

In [24]:
def three_sisters(a,b,c):
    sum = a + b + c

    if(a==b==c):
        return sum * 3
    else:
        return sum

three_sisters(10,20,30)


60

### Example 19

In [30]:
def stringFunc(s):
    if len(s) <= 2:
        return "Not Interested"
    
    else:
        firstTwo = s[:2]
        if firstTwo == "Is":
            return s
        else:
            return f"Is{s}"


print(stringFunc("Isildur"))
print(stringFunc("yunus"))
print(stringFunc("Is"))

Isildur
Isyunus
Not Interested


### Example 20

In [37]:
def stringCopier(s,n):
    return s*n

#stringCopier("Yunus",5)

def largeString(s,n):

    if n <= 0:
        return False
    

    x = ""

    for i in range(n):
        x = x + s
    
    return x


print(largeString("Yunus",5))
print(largeString("yunus",-1))

    

YunusYunusYunusYunusYunus
False


### Example 21

In [39]:
x = int(input("Please give a number: "))


if x%2 == 0:
    print("This Number is even") 
else:
    print("This Number is odd") 

This Number is odd


### Example 22

In [50]:
def four_finder(i):
    tempList = list(i)
    return tempList.count(4)

print(four_finder([12,13,14,4,4]))

def foru_finder_new(i):

    count = 0
    
    for v in i:
        if v==4:
            count = count + 1

    return count 

print(foru_finder_new([4,0,4,3,4,2]))


2
3


### Example 23

In [52]:
def weirdStringFuntion(s,n):
    if len(s) < 2:
        emptyString = ""
        for i in range(n):
            emptyString = emptyString + s
        return emptyString

    else:
        neededPart = s[:2]
        emptyString = ""
        for i in range(n):
            emptyString = emptyString + s
        
        return emptyString

print(weirdStringFuntion("yunus",10))
print(weirdStringFuntion("a",4))





yunusyunusyunusyunusyunusyunusyunusyunusyunusyunus
aaaa


### Example 24

In [59]:
def vowelOrNot(l):
    vowelS = ["A","E","I","O","U"]
    vowelSC = list()

    for e in vowelS:
        vowelSC.append(e.lower())

    if l in vowelS or l in vowelSC:
        return "It is NOWEL"
    else:
        return "It is NOT NOWEL"

print(vowelOrNot("a"))
print(vowelOrNot("I"))
print(vowelOrNot("x"))




It is NOWEL
It is NOWEL
It is NOT NOWEL


### Example 25

In [60]:
def magicFunc(e,l):
    if e in l:
        return True
    else:
        return False

print(magicFunc(5,[5,10,15]))
print(magicFunc(1,[2,3,4,5,6]))

True
False


### Example 26

In [61]:
def histogram_creator(ob,hT):
    for n in hT:
        print(ob*n)

histogram_creator("@",[1,2,3,4,5,4,3,2,1])


@
@@
@@@
@@@@
@@@@@
@@@@
@@@
@@
@


### Example 27

In [63]:
def concatenateFunc(l):
    sum = ""
    for e in l:
        sum = sum + str(e)
    return sum

print(concatenateFunc([1,2,1,"yunus","elon",14,13,-1,]))

121yunuselon1413-1


### Example 28

In [76]:
def listEvener(l):
    for e in l:
        if e != 237:
            if e %2 == 0:
                print(e)
        else:
            print(237)
            break
        

listEvener([386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217, 
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717, 
    958,743, 527])


386
462
418
344
236
566
978
328
162
758
918
237


### Example 29

In [82]:
color_list_1 = set(["White","Black","Red"])
color_list_2 = set(["Red","Green"])

finalList = []

for c in color_list_1:
    if c not in color_list_2:
        finalList.append(c)
print(finalList)


print(color_list_1.difference(color_list_2))
print(color_list_2.difference(color_list_1))

['Black', 'White']
{'Black', 'White'}
{'Green'}


### Example 30

In [83]:
def calculateAreOfTriangle(b,h):
    return b*h/2

print(calculateAreOfTriangle(10,6))


30.0


### Example 31

In [11]:
def gcdCalculater(n1,n2):
    gcd = 0

    for i in range(min(n1,n2) + 1):
        if i != 0:
            if n1%i == 0 and n2%i == 0:
                gcd = i

    return gcd

print(gcdCalculater(1,5))

1


### Example 32

In [18]:
def lcmCalculater(n1,n2):
    
    bigNumber = max(n1,n2)
    lcm = bigNumber

    while lcm%n1 != 0 or lcm%n2 !=0:
        lcm += 1
    return lcm

print(lcmCalculater(13,91))




91


### Example 33


In [22]:
def weirdSumFunciton(a,b,c):
    if a == b or a == c or b == c:
        return 0
    else:
        return a + b + c
print(weirdSumFunciton(3,3,2))


0


### Example 34

In [23]:
def strangeSumFunc(a,b):
    sum = a + b

    if sum in range(15,21):
        return 20

    else:
        return sum

print (strangeSumFunc(3,4))
print(strangeSumFunc(8,9))

7
20


### Example 35

In [24]:
def fiveOrEqualFunc(a,b):
    if a == b or abs(a-b) == 5:
        return True
    else :
        return False

print(fiveOrEqualFunc(10,5))
print(fiveOrEqualFunc(10,10))
print(fiveOrEqualFunc(10,32))


True
True
False


### Example 36

In [28]:
def sumFunc(a,b):
    if isinstance(a,int) and isinstance(b,int):
        return a + b
    else:
        return "give integer values only"
print(sumFunc(3,4))
print(sumFunc(5,5.1))
print(sumFunc(2.1,2.1))
print(sumFunc("c","y"))

7
give integer values only
give integer values only
give integer values only


### Example 37

In [35]:
def personal_details():
    name, age, adress = "Yunus",19,"Istanbul/Ümraniye"
    return "Name: {} \nAge: {} \nAdress: {}".format(name,age,adress)

print(personal_details())

Name: Yunus 
Age: 19 
Adress: Istanbul/Ümraniye


### Example 38

In [36]:
def strangeFunc(a,b):
    sum = a + b
    return sum **2

print(strangeFunc(10,5))


225


### Example 39

In [38]:
def interestRateCalculater(p,r,n,t):
    return round(((1+r/n)*p)**t)

interestRateCalculater(1,2,3,4)

8

### Example 40

In [45]:
from math import sqrt


def twoPointDistance(p1,p2):
    xDistance = abs(p1[0]-p2[0])
    yDistance = abs(p1[1]-p2[1])

    return sqrt(xDistance**2 + yDistance**2)

print(twoPointDistance((5,0),(5,8)))

8.0


### Example 41

In [4]:
import os

print(os.path.exists("/Users/yunusmerve/Documents/MerveninFelsefeÖdevi.docx"))

True


### Example 42


In [5]:
import platform

print(platform.architecture()[0])

64bit


### Example 43

In [6]:
import os
import platform

print(f"""
Name of the Operating System: {os.name}
Name of the OS System: {platform.system()}
Version of the Operating System: {platform.release()}
""")


Name of the Operating System: posix
Name of the OS System: Darwin
Version of the Operating System: 21.6.0



### Example 44

In [7]:
import site
print(site.getsitepackages())

['/Users/yunusmerve/opt/anaconda3/lib/python3.9/site-packages']


### Example 45

In [9]:
import os
print(os.system('ls'))

01 - Variables.ipynb
02-Listeler[].ipynb
03-Sozlukler{}.ipynb
04-Setler(Diziler){}.ipynb
05-Tuple().ipynb
06-Boolean.ipynb
07-EgerKontrolleri.ipynb
08-ForLoop.ipynb
09-ContinueBreakPass.ipynb
10-WhileLoop.ipynb
11- VeriBilimiMetotlar.ipynb
12-FonksiyonlarMethodlar.ipynb
13-FaydaliFonksiyonlar.ipynb
14-Kapsam(Scope).ipynb
15-HesapMakinesi.ipynb
16-OOP.ipynb
17-OOP-OzelMethodlar.ipynb
18-HataHandling.ipynb
19-Moduller.ipynb
20-NumpyGiris.ipynb
21-NumpyOperasyonlar.ipynb
22-PandasGiris.ipynb
23-DataFramePandas.ipynb
24-PandasOperasyonlar.ipynb
26-PandasExcel.ipynb
27-MatplotlibGiris.ipynb
ExamplesP1_150.ipynb
PandasOperasyonDevamı.ipynb
maasBilgisi.xlsx
tamMaas.xlsx
0


### Example 46

In [12]:
import os
print(f"Current File Name: {os.path.realpath(__file__)}")

NameError: name '__file__' is not defined

### Example 47

In [13]:
import multiprocessing

print(multiprocessing.cpu_count())

8


### Example 48

In [15]:
x = "1453.12"

y = float(x)
z = int(y)

print(f"""
{x}
{y}
{z}
""")


1453.12
1453.12
1453



### Example 49

In [16]:
import os

path = "/Users/yunusmerve/Desktop/GitGenel"
dir_list = os.listdir(path)

print(dir_list)


['RebaseTestProjesi', '.DS_Store', 'JavaKitabı', 'Kitap', 'GitKursu', 'KotlinKitabi']


### Example 50

In [22]:
for i in range(5):
    print("*", end="")

print("\nyunus",end=" korkmaz")
print("c")

*****
yunus korkmazc


### Example 51

In [27]:
import cProfile
def sumFunc():
    for e in range(5):
        print("x",end="")
cProfile.run('sumFunc()')

xxxxx         157 function calls in 0.001 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.001    0.001 2694685293.py:2(sumFunc)
        1    0.000    0.000    0.001    0.001 <string>:1(<module>)
       11    0.000    0.000    0.001    0.000 iostream.py:208(schedule)
       10    0.000    0.000    0.000    0.000 iostream.py:420(_is_master_process)
       10    0.000    0.000    0.000    0.000 iostream.py:439(_schedule_flush)
       10    0.000    0.000    0.001    0.000 iostream.py:502(write)
       11    0.000    0.000    0.000    0.000 iostream.py:97(_event_pipe)
       11    0.001    0.000    0.001    0.000 socket.py:480(send)
       11    0.000    0.000    0.000    0.000 threading.py:1059(_wait_for_tstate_lock)
       11    0.000    0.000    0.000    0.000 threading.py:1126(is_alive)
       11    0.000    0.000    0.000    0.000 threading.py:529(is_set)
        1    0.000    0.000    0.00

### Example 52

In [28]:
import sys
print("Very big error", file=sys.stderr)

Very big error


### Example 53

In [33]:
import os
print(os.environ)

environ({'SHELL': '/bin/zsh', 'TMPDIR': '/var/folders/mh/x5vmc6194szf246rdvs1s6n40000gn/T/', 'CONDA_SHLVL': '1', 'CONDA_PROMPT_MODIFIER': '(base) ', 'PYTHONUNBUFFERED': '1', 'MallocNanoZone': '0', 'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined', 'USER': 'yunusmerve', 'PYTHONIOENCODING': 'utf-8', 'COMMAND_MODE': 'unix2003', 'CONDA_EXE': '/Users/yunusmerve/opt/anaconda3/bin/conda', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.0LHtbuAyjQ/Listeners', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'ELECTRON_RUN_AS_NODE': '1', 'VSCODE_AMD_ENTRYPOINT': 'vs/workbench/api/node/extensionHostProcess', '_CE_CONDA': '', 'CONDA_ROOT': '/Users/yunusmerve/opt/anaconda3', 'PATH': '/Users/yunusmerve/opt/anaconda3/bin:/Users/yunusmerve/opt/anaconda3/condabin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Users/yunusmerve/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands', '__CFBundleIdentifier': 'com.microsoft.VSCode', 'CONDA_PREFIX': '/Users

### Example 54

In [34]:
import getpass
print(getpass.getuser())

yunusmerve


### Example 55

In [36]:
import socket
hostname = socket.gethostname()
IPadress = socket.gethostbyname(hostname)

print(f"Our IP Adress: {IPadress}")

Our IP Adress: 127.0.0.1


## RNA Question

In [42]:
a = "yunus"
listOfa = list(a)
listOfa[4] =  "ş"

aN = ''.join(listOfa)
aN

'yunuş'

In [44]:
def rnaConverter(DNA):
    tempList = list(DNA)
    editingList = tempList
    index = -1
    for l in tempList:
        index += 1
        if l == "G":
            editingList[index] = "C"
        elif l == "C":
            editingList[index] = "G"
        elif l == "T":
            editingList[index] = "A"
        elif l == "A":
            editingList[index] = "U"
    return ''.join(editingList)

print(rnaConverter("AGGT TAAA AGCT TGCA ADGC ADGC TAAA GCAA TAAA GCAA AGGG"))
            


UCCA AUUU UCGA ACGU UDCG UDCG AUUU CGUU AUUU CGUU UCCC


In [1]:
import numpy as np


In [7]:
arr = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [9]:
arr = np.array([[[1,2,3],[2,3,4],[3,4,5],[2,3,4],[2,3,4],[2,3,4]]])
print(arr)

[[[1 2 3]
  [2 3 4]
  [3 4 5]
  [2 3 4]
  [2 3 4]
  [2 3 4]]]


In [10]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
arr = np.array(12, ndmin=5)
print(arr)

[[[[[12]]]]]


In [18]:
arr = np.array([1,2,3], ndmin=1)
print(arr.ndim)

1


In [19]:
print(arr[0])


1


In [22]:
arr = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
2


In [30]:
arr = np.array([[[1,2,3],[1,2,3],[1,2,3]]])

In [31]:
arr.shape

(1, 3, 3)

In [33]:
arr = np.array([1,2,3,4,5,6])

In [34]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
ar = np.array([[1,2],[1,2]])
arr = np.array([[2,3],[2,3]])
a = np.concatenate((arr,ar), axis=0)
#print(a)
b = np.stack((ar,arr),axis=0)
print(b)

[[[1 2]
  [1 2]]

 [[2 3]
  [2 3]]]


In [50]:
myDict = {'y': 12}
myDict["y"]

12