In [2]:
import numpy as np


## Numpy Array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [6]:
type(np.array(benimListem))

numpy.ndarray

In [7]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [8]:
type(matrixListesi)

list

In [9]:
matrixListesi[1][2]

40

In [10]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## aRange

In [11]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Ones

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### LinSpace, başlangıç ve bitiş arasında (ikisi de dahil) bizim belirlediğimiz miktar kadar, aralarında eşit fark bulunan sayılar oluşturur.

In [34]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

# Eye

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random


In [3]:
np.random.randn(8)

array([-0.17975129, -0.37442046, -0.27302253, -0.22302323, -0.71975121,
       -0.04376359,  1.63813998,  0.38231396])

In [4]:
np.random.randn(2)

array([-0.55333326,  0.82200926])

In [5]:
np.random.randn(2,2)

array([[-0.18163129,  1.53193512],
       [-0.37225122, -0.64541302]])

In [7]:
np.random.randn(1,1)

array([[-0.78689565]])

In [11]:
np.random.randint(1,10)

2

In [13]:
np.random.randint(1,300
                  ,5)

array([173,  45, 191,  84,  69])

In [14]:
benimNumpyDizim = np.arange(30)

In [15]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
benimNumpyDizim = np.random.randint(0,300,30)

In [19]:
benimRandomDizim

array([169,   0,  70, 168, 129, 241,  11,  63, 259,  48, 253, 288, 264,
       247, 290,   9,  36,  89,   9, 158])

## Numpy Dizi Methodları


In [20]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
benimNumpyDizim.reshape(5,6)

array([[295, 114, 165,  28, 137,   2],
       [  0, 125, 251, 273,  75,  63],
       [122, 242,  84, 123, 271, 177],
       [279, 138, 103, 296, 166, 149],
       [  5, 106,  68, 278,  47, 177]])

In [32]:
benimNumpyDizim.max()

296

In [33]:
benimNumpyDizim.min()

0

In [34]:
benimRandomDizim.argmax()

14

In [35]:
benimNumpyDizim.argmin()

6

In [36]:
benimNumpyDizim.shape

(30,)

In [37]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [40]:
reshapeDizim.shape

(5, 6)